#!/bin/bash
echo "=== PORTX Environment Debug ==="
echo "GIT_BASH_ROOT=$(find_git_bash_root)"
echo "USER=portx"
echo "PORTX_HOME=\$GIT_BASH_ROOT/home/\$USER"
echo ""
echo "=== Calculated Values ==="
GIT_BASH_ROOT=$(find_git_bash_root)
echo "GIT_BASH_ROOT=$GIT_BASH_ROOT"
echo "PORTX_HOME=$GIT_BASH_ROOT/home/portx"
echo ""
echo "=== Directory Tests ==="
echo "Git Bash root exists: $(test -d "$GIT_BASH_ROOT" && echo "YES" || echo "NO")"
echo "PORTX home exists: $(test -d "$GIT_BASH_ROOT/home/portx" && echo "YES" || echo "NO")"
echo ""
echo "=== Claude Test ==="
echo "Testing claude command..."
claude --version 2>&1 || echo "Claude failed"