#!/bin/bash
# PORTX: clamav/freshclam
case "$(uname -sr)" in
    [Ll]inux*[Mm]icrosoft*) r="/mnt/c/App/PORTX"; p="false" ;;
    [Mm][Ii][Nn][Gg][Ww]*|[Mm][Ss][Yy][Ss]*) r="/c/App/PORTX"; p="false" ;;
    [Cc][Yy][Gg][Ww][Ii][Nn]*) r="/cygdrive/c/App/PORTX"; p="cygwin" ;;
    *) r="/c/App/PORTX"; p="false" ;;
esac
args=("$@")
exec "$r/packages/clamav/clamav-1.5.1.win.x64/freshclam.exe" "${args[@]}"